export const playerData = [
  {
    image: require('../assets/player-img-1.png'),
    playerName: 'Chase Daniel (QB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-2.png'),
    playerName: 'Justin Herbert (QB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-3.png'),
    playerName: 'Najee Harris (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-4.png'),
    playerName: 'Rhamondre Stevenson (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-5.png'),
    playerName: 'Damien Harris (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-6.png'),
    playerName: 'Dare Ogunbowale (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-7.png'),
    playerName: 'Rachaad White (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-8.png'),
    playerName: 'Breece Hall (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-1.png'),
    playerName: 'Chase Daniel (QB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-2.png'),
    playerName: 'Justin Herbert (QB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-3.png'),
    playerName: 'Najee Harris (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-4.png'),
    playerName: 'Rhamondre Stevenson (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-5.png'),
    playerName: 'Damien Harris (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-6.png'),
    playerName: 'Dare Ogunbowale (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-7.png'),
    playerName: 'Rachaad White (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-8.png'),
    playerName: 'Breece Hall (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-1.png'),
    playerName: 'Chase Daniel (QB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-2.png'),
    playerName: 'Justin Herbert (QB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-3.png'),
    playerName: 'Najee Harris (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
  {
    image: require('../assets/player-img-4.png'),
    playerName: 'Rhamondre Stevenson (RB)',
    owner: 'Circa Trout',
    positon: 'Linebacker',
    age: '31 years',
    date: 'Sep 10, 2021',
  },
]

export const leagueScoreData = [
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
  {
    image: require('../assets/heat-wave-square-1.png'),
    title: 'Hear Wave Square',
    date: new Date(),
    scores: [1, 2],
  },
]

export const teamCardData = [
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/defiance.png'),
    title: 'Defiance',
    link: 'Twitter: @DeFiance_UFAFL',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/rage.png'),
    title: 'Rage',
    link: 'Alex@sevenseasblockchainsports.com',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/storm_breakers.png'),
    title: 'Storm Breakers',
    link: 'Twitter: @StormBreakersFF',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/the_beast.png'),
    title: 'The Beast',
    link: 'Twitter: @TheBeastUFAFL',
  },
  {
    text: 'Madden',
    direction: 'North',
    imageUrl: require('../assets/teams/circa_sports_trout.png'),
    title: 'Circa Sports Trout',
    link: 'Based in Las Vegas NV Twitter: @CircaTrout',
  },
  {
    text: 'Madden',
    direction: 'North',
    imageUrl: require('../assets/teams/outcasts.png'),
    title: 'Outcasts',
    link: 'Bufafloutcasts@gmail.com',
  },
  {
    text: 'Madden',
    direction: 'North',
    imageUrl: require('../assets/teams/rowdys.png'),
    title: 'Rowdys',
    link: 'Twitter: @rowdysfootball',
  },
  {
    text: 'Madden',
    direction: 'North',
    imageUrl: require('../assets/teams/the_flying_foxes.png'),
    title: 'The Flying Foxes',
    link: '',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/canwest_gladiators.png'),
    title: 'CanWest Gladiators',
    link: 'chad@canwestfantasysports.comTwitter: @GladiatorsUFAFL',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/kingsmen.png'),
    title: 'Kingsmen',
    link: '',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/legion.png'),
    title: 'Legion',
    link: 'legion.ufafl@gmail.comTwitter: @LEGIONUFAFL',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/the_resistance.png'),
    title: 'The Resistance',
    link: 'TheResistanceGM@yahoo.com',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/empire.png'),
    title: 'Empire',
    link: 'Twitter: @THEEMPIREFANTA1',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/kraken.png'),
    title: 'Kraken',
    link: 'Twitter: @KrakenUFAFL',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/seven_angles.png'),
    title: 'Seven7 Angels',
    link: 'djones@hedgeye.COM',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/silverbacks.png'),
    title: 'Silverbacks',
    link: 'silverbacks.ufafl@gmail.com',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/doom.png'),
    title: 'Doom',
    link: 'Twitter: @DoomUFAFL',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/gridiron_seals.png'),
    title: 'Gridiron Seals',
    link: 'Based in Regina, SK, CanadaTwitter: @GridIronSeals',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/tiger_sharks.png'),
    title: 'Tiger Sharks',
    link: '',
  },
  {
    text: 'Madden',
    direction: 'East',
    imageUrl: require('../assets/teams/monsters.png'),
    title: 'Monsters',
    link: 'Twitter: @turfmonsters21',
  },
]

export const playerStatsData = [
  {
    name: 'Mahomes, Patrick KCC QB',
    pts: 650.3,
    avg: 38.2529,
    status: 'Paradise Block Hawks',
    bye: 8,
    salary: 35793382,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
  {
    name: 'Allen, Josh BUF QB',
    pts: 607.75,
    avg: 37.9844,
    status: 'TDU',
    bye: 7,
    salary: 16372282,
    data: [
      {
        1: 54.95,
        2: 28.75,
        3: 26.3,
        4: 38.55,
        5: 47.8,
        6: 32.6,
        7: 42.15,
        8: 8,
        9: 50.1,
        10: 49.45,
        11: 41.35,
        12: 29.6,
        13: 27.55,
        14: 35.35,
        15: 48.05,
        16: 33.5,
        17: 41.2,
        18: 23.05,
      },
    ],
  },
]

export const leagueStandingData = [
  {
    mainTitle: 'The Manning Conference - North',
    data: [
      {
        imageUrl: require('../assets/dragons-red-zone-square-1.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/pradise.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/timber.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/surfdogs.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
    ],
  },
  {
    mainTitle: 'The Manning Conference - EAST',
    data: [
      {
        imageUrl: require('../assets/dragons-red-zone-square-1.png'),
        title: 'Doom',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/pradise.png'),
        title: 'GRIDIRON SEALS',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/timber.png'),
        title: 'TIGER SHARKS',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/surfdogs.png'),
        title: 'TURF MONSTERS',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
    ],
  },
  {
    mainTitle: 'The Manning Conference - South',
    data: [
      {
        imageUrl: require('../assets/dragons-red-zone-square-1.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/pradise.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/timber.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/surfdogs.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
    ],
  },
  {
    mainTitle: 'The Manning Conference - West',
    data: [
      {
        imageUrl: require('../assets/dragons-red-zone-square-1.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/pradise.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/timber.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/surfdogs.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
    ],
  },
  {
    mainTitle: 'JOHN MADDEN Conference - North',
    data: [
      {
        imageUrl: require('../assets/dragons-red-zone-square-1.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/pradise.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/timber.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/surfdogs.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
    ],
  },
  {
    mainTitle: 'JOHN MADDEN Conference - East',
    data: [
      {
        imageUrl: require('../assets/dragons-red-zone-square-1.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/pradise.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/timber.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/surfdogs.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
    ],
  },
  {
    mainTitle: 'JOHN MADDEN Conference - South',
    data: [
      {
        imageUrl: require('../assets/dragons-red-zone-square-1.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/pradise.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/timber.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/surfdogs.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
    ],
  },
  {
    mainTitle: 'JOHN MADDEN Conference - West',
    data: [
      {
        imageUrl: require('../assets/dragons-red-zone-square-1.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/pradise.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/timber.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
      {
        imageUrl: require('../assets/surfdogs.png'),
        title: 'Red Zone Dragons',
        tableData: [
          {
            key: '1',
            wlt: '8-9-0',
            pct: '.471',
            gb: '3.0',
            strk: 'W1',
            pf: '4686.125',
            avgpf: '260.3',
            pa: '4919.300',
            avgpa: '289.4',
            divwlt: '4-2-0',
            confwlt: '6-6-0',
          },
        ],
      },
    ],
  },
]

export const transactionData = [
  {
    key: 1,
    franchise: 'The Beast',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 2,
    franchise: 'Blockchain Bounty Hunters',
    type: 'Injured Reserve',
    transaction: ['Deactivated Boone, Mike DEN RB; Jackson, Donte CAR CB'],
    date: new Date(),
  },
  {
    key: 3,
    franchise: 'Blockchain Bounty Hunters',
    type: 'Taxi Squad',
    transaction: ['Promoted Kirkwood, Keith NOS WR; Robinson, Kenny PIT S,'],
    date: new Date(),
  },
  {
    key: 4,
    franchise: 'The Resistance (C)',
    type: 'Add/Drop',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 5,
    franchise: 'Red Zone Dragons',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 6,
    franchise: 'Red Zone Dragons',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 7,
    franchise: 'Red Zone Dragons',
    type: 'Taxi Squad',
    transaction: ['Promoted Lewis, Terrell CHI LB', 'Demoted Tuszka, Derrek LAC LB'],
    date: new Date(),
  },
  {
    key: 8,
    franchise: 'Kingsmen',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 9,
    franchise: 'Kingsmen',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 10,
    franchise: 'Empire',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 11,
    franchise: 'The Beast',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 12,
    franchise: 'Blockchain Bounty Hunters',
    type: 'Injured Reserve',
    transaction: ['Deactivated Boone, Mike DEN RB; Jackson, Donte CAR CB'],
    date: new Date(),
  },
  {
    key: 13,
    franchise: 'Blockchain Bounty Hunters',
    type: 'Taxi Squad',
    transaction: ['Promoted Kirkwood, Keith NOS WR; Robinson, Kenny PIT S,'],
    date: new Date(),
  },
  {
    key: 14,
    franchise: 'The Resistance (C)',
    type: 'Add/Drop',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 15,
    franchise: 'Red Zone Dragons',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 16,
    franchise: 'Red Zone Dragons',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 17,
    franchise: 'Red Zone Dragons',
    type: 'Taxi Squad',
    transaction: ['Promoted Lewis, Terrell CHI LB', 'Demoted Tuszka, Derrek LAC LB'],
    date: new Date(),
  },
  {
    key: 18,
    franchise: 'Kingsmen',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 19,
    franchise: 'Kingsmen',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 20,
    franchise: 'Empire',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 21,
    franchise: 'The Beast',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 22,
    franchise: 'Blockchain Bounty Hunters',
    type: 'Injured Reserve',
    transaction: ['Deactivated Boone, Mike DEN RB; Jackson, Donte CAR CB'],
    date: new Date(),
  },
  {
    key: 23,
    franchise: 'Blockchain Bounty Hunters',
    type: 'Taxi Squad',
    transaction: ['Promoted Kirkwood, Keith NOS WR; Robinson, Kenny PIT S,'],
    date: new Date(),
  },
  {
    key: 24,
    franchise: 'The Resistance (C)',
    type: 'Add/Drop',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 25,
    franchise: 'Red Zone Dragons',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 26,
    franchise: 'Red Zone Dragons',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 27,
    franchise: 'Red Zone Dragons',
    type: 'Taxi Squad',
    transaction: ['Promoted Lewis, Terrell CHI LB', 'Demoted Tuszka, Derrek LAC LB'],
    date: new Date(),
  },
  {
    key: 28,
    franchise: 'Kingsmen',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 29,
    franchise: 'Kingsmen',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
  {
    key: 30,
    franchise: 'Empire',
    type: 'Taxi Squad',
    transaction: ['Demoted Bolton, Nick KCC LB; White, Kyzir PHI LB'],
    date: new Date(),
  },
]

export const liveScoreData = [
  {
    title: 'PARADISE BLACK HAWKS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'PARADISE BLACK HAWKS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
  {
    title: 'GRIDIRON SEALS',
    starters: '',
    starter: 0,
    nonStarter: '',
  },
]

export const scheduleData = [
  {
    title: 'Week 1 Head-To-Head Results',
    data: [
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
    ],
  },
  {
    title: 'Week 1 Head-To-Head Results',
    data: [
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
    ],
  },
  {
    title: 'Week 1 Head-To-Head Results',
    data: [
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
    ],
  },
  {
    title: 'Week 1 Head-To-Head Results',
    data: [
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
    ],
  },
  {
    title: 'Week 1 Head-To-Head Results',
    data: [
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
    ],
  },
  {
    title: 'Week 1 Head-To-Head Results',
    data: [
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Heat Wave',
          score: '425.825',
        },
        team2: {
          matchup: 'GhostRiders',
          score: '191.650',
        },
      },
      {
        team1: {
          matchup: 'Paradise Black Hawks',
          score: '320.875',
        },
        team2: {
          matchup: 'SurfDogs',
          score: '238.150',
        },
      },
      {
        team1: {
          matchup: 'Tiger Sharks',
          score: '295.475',
        },
        team2: {
          matchup: 'Doom',
          score: '325.900',
        },
      },
    ],
  },
]
