export const draftData = [
  {
    teamId: '64e5ee7d6e36d01a688fc6d2', // Circa Sports Trout
    draft: [
      "24' Circa Sports Trout 1st Round",
      "24' Circa Sports Trout 2nd Round",
      "24' Circa Sports Trout 3rd Round",
      "24' Circa Sports Trout 4th Round",
      "24' Circa Sports Trout 5th Round",
      "24' Circa Sports Trout 6th Round",
      "24' Circa Sports Trout 7th Round",

      "25' SB Hurricanes 1st Round",
      "25' Circa Sports Trout 1st Round",
      "25' Circa Sports Trout 2nd Round",
      "25' Circa Sports Trout 3rd Round",
      "25' Circa Sports Trout 4th Round",
      "25' Circa Sports Trout 5th Round",
      "25' Circa Sports Trout 6th Round",
      "25' Circa Sports Trout 7th Round",

      "26' Circa Sports Trout 1st Round",
      "26' Circa Sports Trout 2nd Round",
      "26' Circa Sports Trout 3rd Round",
      "26' Circa Sports Trout 4th Round",
      "26' Circa Sports Trout 5th Round",
      "26' Circa Sports Trout 6th Round",
      "26' Circa Sports Trout 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6cf', // South Beach Hurricanes
    draft: [
      "24' CanWest 1st Round",
      "24' Legion 1st Round",
      "24' FanCentric 2nd Round",
      "24' Kracken 2nd Roun",
      "24' SB Hurricanes 3rd Round",
      "24' SB Hurricanes 4th Round",
      "24' SB Hurricanes 5th Round",
      "24' SB Hurricanes 6th Round",
      "24' SB Hurricanes 7th Round",

      "25' Chargers 1st Round",
      "25' FanCentric 1st Round",
      "25' Ghostriders 1st Round",
      "25' Thrashers 1st Round",
      "25' Ghostriders 2nd Round",
      "25' Toppem Spoilers 3rd Round",
      "25' SB Hurricanes 3rd Round",
      "25' SB Hurricanes 4th Round",
      "25' SB Hurricanes 5th Round",
      "25' SB Hurricanes 6th Round",
      "25' SB Hurricanes 7th Round",

      "26' SB Hurricanes 1st Round",
      "26' SB Hurricanes 2nd Round",
      "26' SB Hurricanes 3rd Round",
      "26' SB Hurricanes 4th Round",
      "26' SB Hurricanes 5th Round",
      "26' SB Hurricanes 6th Round",
      "26' SB Hurricanes 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6d3', // Toppem Spoilers
    draft: [
      "24' Timberwolves 1st Round",
      "24' Resistance 2nd Round",
      "24' Toppem Spoilers 3rd Round",
      "24' Toppem Spoilers 4th Round",
      "24' Toppem Spoilers 5th Round",
      "24' Toppem Spoilers 6th Round",
      "24' Toppem Spoilers 7th Round",

      "25' Toppem Spoilers 4th Round",
      "25' Toppem Spoilers 5th Round",
      "25' Toppem Spoilers 6th Round",
      "25' Toppem Spoilers 7th Round",

      "26' Toppem Spoilers 1st Round",
      "26' Toppem Spoilers 2nd Round",
      "26' Toppem Spoilers 3rd Round",
      "26' Toppem Spoilers 4th Round",
      "26' Toppem Spoilers 5th Round",
      "26' Toppem Spoilers 6th Round",
      "26' Toppem Spoilers 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6ee', // Kracken
    draft: [
      "24' Hammerheads 1st Round",
      "24' Kracken 3rd Round",
      "24' Kracken 4th Round",
      "24' Kracken 5th Round",
      "24' Kracken 6th Round",
      "24' Kracken 7th Round",

      "25' CanWest 1st Round",
      "25' Kracken 2nd Round",
      "25' CanWest 2nd Round",
      "25' Kracken 3rd Round",
      "25' CanWest 3rd Roun",
      "25' Kracken 4th Round",
      "25' Kracken 5th Round",
      "25' Kracken 6th Round",
      "25' Kracken 7th Round",

      "26' Kracken 1st Round",
      "26' Kracken 2nd Round",
      "26' Kracken 3rd Round",
      "26' Kracken 4th Round",
      "26' Kracken 5th Round",
      "26' Kracken 6th Round",
      "26' Kracken 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6dc', // Atlanta Legion
    draft: [
      "24' Legion 4th Round",
      "24' Legion 5th Round",
      "24' Gridiron 5th Round",
      "24' Legion 6th Round",
      "24' Legion 7th Round",

      "25' Legion 1st Round",
      "25' Legion 2nd Round",
      "25' Legion 3rd Round",
      "25' Legion 4th Round",
      "25' Legion 5th Round",
      "25' Legion 6th Round",
      "25' Legion 7th Round",

      "26' Legion 1st Round",
      "26' Legion 2nd Round",
      "26' Legion 3rd Round",
      "26' Legion 4th Round",
      "26' Legion 5th Round",
      "26' Legion 6th Round",
      "26' Legion 7th Round",
      // "26' Legion 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6e8', // Rowdy
    draft: [
      "24' Beast 1st Round",
      "24' Ghostriders 2nd Round",
      "24' Rowdys 3rd Round",
      "24' Rowdys 4th Round",
      "24' Rowdys 5th Round",
      "24' Rowdys 6th Round",
      "24' Rowdys 7th Round",

      "25' Rowdys 1st Round",
      "25' Rowdys 2nd Round",
      "25' Rowdys 3rd Round",
      "25' Rowdys 4th Round",
      "25' Rowdys 5th Round",
      "25' Rowdys 6th Round",
      "25' Rowdys 7th Round",

      "26' Rowdys 1st Round",
      "26' Rowdys 2nd Round",
      "26' Rowdys 3rd Round",
      "26' Rowdys 4th Round",
      "26' Rowdys 5th Round",
      "26' Rowdys 6th Round",
      "26' Rowdys 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6e0', // Sportstopia
    draft: [
      "24' Sportstopia 1st Round",
      "24' Sportstopia 3rd Round",
      "24' Sportstopia 4th Round",
      "24' Sportstopia 5th Round",
      "24' Sportstopia 6th Round",
      "24' Sportstopia 7th Round",

      "25' SB Hurricanes 2nd Round",
      "25' Thrashers 2nd Round",
      "25' Sportstopia 3rd Round",
      "25' Sportstopia 4th Round",
      "25' Sportstopia 5th Round",
      "25' Sportstopia 6th Round",
      "25' Sportstopia 7th Round",

      "26' Sportstopia 1st Round",
      "26' Sportstopia 2nd Round",
      "26' Sportstopia 3rd Round",
      "26' Sportstopia 4th Round",
      "26' Sportstopia 5th Round",
      "26' Sportstopia 6th Round",
      "26' Sportstopia 7th Round",
      // "26' Sportstopia 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6e7', // Outcasts
    draft: [
      "24' Red Zone 2nd Round",
      "24' Outcast 3rd Round",
      "24' Outcast 4th Round",
      "24' Outcast 5th Round",
      "24' Outcast 6th Round",
      "24' Outcast 7th Round",

      "25' Outcasts 1st Round",
      "25' Outcasts 2nd Round",
      "25' Red Zone 2nd Round",
      "25' Outcasts 3rd Round",
      "25' Outcasts 4th Round",
      "25' Outcasts 5th Round",
      "25' Outcasts 6th Round",
      "25' Outcasts 7th Round",

      "26' Outcasts 1st Round",
      "26' Outcasts 2nd Round",
      "26' Outcasts 3rd Round",
      "26' Outcasts 4th Round",
      "26' Outcasts 5th Round",
      "26' Outcasts 6th Round",
      "26' Outcasts 7th Round",
      // "26' Outcasts 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6d5', // Hydra
    draft: [
      "24' Hydra 1st Round",
      "24' Hydra 3rd Round",
      "24' Hydra 4th Round",
      "24' Hydra 5th Round",
      "24' Hydra 6th Round",
      "24' Hydra 7th Round",

      "25' Hydra 1st Round",
      "25' Hydra 2nd Round",
      "25' Hydra 3rd Round",
      "25' Hydra 4th Round",
      "25' Hydra 5th Round",
      "25' Hydra 6th Round",
      "25' Hydra 7th Round",

      "26' Hydra 1st Round",
      "26' Hydra 2nd Round",
      "26' Hydra 3rd Round",
      "26' Hydra 4th Round",
      "26' Hydra 5th Round",
      "26' Hydra 6th Round",
      "26' Hydra 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6d9', // Tiger Sharks
    draft: [
      "24' Tiger Sharks 1st Round",
      "24' Tiger Sharks 2nd Round",
      "24' SB Hurricanes 2nd Round",
      "24' Tiger Sharks 3rd Round",
      "24' Tiger Sharks 4th Round",
      "24' Tiger Sharks 5th Round",
      "24' Tiger Sharks 6th Round",
      "24' Tiger Sharks 7th Round",

      "25' Tiger Sharks 1st Round",
      "25' Tiger Sharks 2nd Round",
      "25' Tiger Sharks 3rd Round",
      "25' Tiger Sharks 4th Round",
      "25' Tiger Sharks 5th Round",
      "25' Tiger Sharks 6th Round",
      "25' Tiger Sharks 7th Round",

      "26' Tiger Sharks 1st Round",
      "26' Tiger Sharks 2nd Round",
      "26' Tiger Sharks 3rd Round",
      "26' Tiger Sharks 4th Round",
      "26' Tiger Sharks 5th Round",
      "26' Tiger Sharks 6th Round",
      "26' Tiger Sharks 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6d8', // Tampa Thrasher
    draft: [
      "24' Thrashers 3rd Round",
      "24' Thrashers 4th Round",
      "24' Thrashers 5th Round",
      "24' Thrashers 6th Round",
      "24' Thrashers 7th Round",

      "25' FanCentric 2nd Round",
      "25' Toppem Spoilers 2nd Round",
      "25' FanCentric 3rd Round",
      "25' Thrashers 4th Round",
      "25' Thrashers 5th Round",
      "25' Thrashers 6th Round",
      "25' Thrashers 7th Round",

      "26' Thrashers 1st Round",
      "26' Thrashers 2nd Round",
      "26' Thrashers 3rd Round",
      "26' Thrashers 4th Round",
      "26' Thrashers 5th Round",
      "26' Thrashers 6th Round",
      "26' Thrashers 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6d6', // VooDoo
    draft: [
      "24' 77 Angels 1st Round",
      "24' Warriors 1st Round",
      "24' 77 Angels 2nd Round",
      "24' Kingsmen 2nd Round",
      "24' 77 Angels 3rd Round",
      "24' 77 Angels 4th Round",
      "24' 77 Angels 5th Round",
      "24' 77 Angels 6th Round",
      "24' 77 Angels 7th Round",

      "25' 77 Angels 1st Round",
      "25' 77 Angels 2nd Round",
      "25' 77 Angels 3rd Round",
      "25' 77 Angels 4th Round",
      "25' 77 Angels 5th Round",
      "25' 77 Angels 6th Round",
      "25' 77 Angels 7th Round",

      "26' 77 Angels 1st Round",
      "26' 77 Angels 2nd Round",
      "26' 77 Angels 3rd Round",
      "26' 77 Angels 4th Round",
      "26' 77 Angels 5th Round",
      "26' 77 Angels 6th Round",
      "26' 77 Angels 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6d4', // CanWest
    draft: [
      "24' DeFiance 1st Round",
      "24' FanCentric 1st Round",
      "24' Kracken 1st Round",
      "24' Ghostriders 1st Round",
      "24' Thrashers 1st Round",
      "24' Turf Monsters 1st Round",
      "24' Toppem Spoilers 1st Round",
      "24' DeFiance 2nd Round",
      "24' CanWest 3rd Round",
      "24' CanWest 4th Round",
      "24' CanWest 5th Round",
      "24' CanWest 3rd Round",
      "24' CanWest 4th Round",
      "24' CanWest 5th Round",
      "24' CanWest 6th Round",
      "24' CanWest 7th Round",

      "25' Kracken 1st Round",
      "25' CanWest 4th Round",
      "25' CanWest 5th Round",
      "25' CanWest 6th Round",
      "25' CanWest 7th Round",

      "26' CanWest 1st Round",
      "26' CanWest 2nd Round",
      "26' CanWest 3rd Round",
      "26' CanWest 4th Round",
      "26' CanWest 5th Round",
      "26' CanWest 6th Round",
      "26' CanWest 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6eb', // Silverbacks
    draft: [
      "24' Silverbacks 1st Round",
      "24' Silverbacks 2nd Round",
      "24' Silverbacks 3rd Round",
      "24' Silverbacks 4th Round",
      "24' Silverbacks 5th Round",
      "24' Silverbacks 6th Round",
      "24' Silverbacks 7th Round",

      "25' Silverbacks 1st Round",
      "25' Silverbacks 2nd Round",
      "25' Valkyries 2nd Round",
      "25' Silverbacks 3rd Round",
      "25' Rowdys 3rd Round",
      "25' Silverbacks 4th Round",
      "25' Silverbacks 5th Round",
      "25' Silverbacks 6th Round",
      "25' Silverbacks 7th Round",

      "26' Silverbacks 1st Round",
      "26' Silverbacks 2nd Round",
      "26' Silverbacks 3rd Round",
      "26' Silverbacks 4th Round",
      "26' Silverbacks 5th Round",
      "26' Silverbacks 6th Round",
      "26' Silverbacks 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6ec', // Resistance
    draft: [
      "24' Resistance 1st Round",
      "24' CanWest 2nd Round",
      "24' Hammerheads 2nd Round",
      "24' Rowdys 2nd Round",
      "24' Resistance 3rd Round",
      "24' Silverbacks 4th Round",
      "24' Silverbacks 5th Round",
      "24' Silverbacks 6th Round",
      "24' Silverbacks 7th Round",

      "25' Resistance 1st Round",
      "25' Red Zone 1st Round",
      "25' Resistance 2nd Round",
      "25' Resistance 3rd Roun",
      "25' Red Zone 3rd Round",
      "25' Resistance 4th Round",
      "25' Resistance 5th Round",
      "25' Resistance 6th Round",
      "25' Resistance 7th Round",

      "26' Resistance 1st Round",
      "26' Resistance 2nd Round",
      "26' Resistance 3rd Round",
      "26' Resistance 4th Round",
      "26' Resistance 5th Round",
      "26' Resistance 6th Round",
      "26' Resistance 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6e2', // DeFiance
    draft: [
      "24' DeFiance 2nd Round",
      "24' DeFiance 3rd Round",
      "24' DeFiance 4th Round",
      "24' DeFiance 5th Round",
      "24' DeFiance 6th Round",
      "24' DeFiance 7th Round",

      "25' DeFiance 1st Round",
      "25' DeFiance 2nd Round",
      "25' DeFiance 3rd Round",
      "25' DeFiance 4th Round",
      "25' DeFiance 5th Round",
      "25' DeFiance 6th Round",
      "25' DeFiance 7th Round",

      "26' DeFiance 1st Round",
      "26' DeFiance 2nd Round",
      "26' DeFiance 3rd Round",
      "26' DeFiance 4th Round",
      "26' DeFiance 5th Round",
      "26' DeFiance 6th Round",
      "26' DeFiance 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6d0', // Gridiron
    draft: [
      "24' Gridiron 1st Round",
      "24' Gridiron 3rd Round",
      "24' Legion 3rd Round",
      "24' Gridiron 4th Round",
      "24' Gridiron 6th Round",
      "24' Gridiron 7th Round",

      "25' Gridiron 1st Round",
      "25' Gridiron 2nd Round",
      "25' Gridiron 3rd Round",
      "25' Gridiron 4th Round",
      "25' Gridiron 5th Round",
      "25' Gridiron 6th Round",
      "25' Gridiron 7th Round",

      "26' Gridiron 1st Round",
      "26' Gridiron 2nd Round",
      "26' Gridiron 3rd Round",
      "26' Gridiron 4th Round",
      "26' Gridiron 5th Round",
      "26' Gridiron 6th Round",
      "26' Gridiron 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6e5', // Chargers
    draft: [
      "24' Charger 1st Round",
      "24' Charger 2nd Round",
      "24' Charger 3rd Round",
      "24' Charger 4th Round",
      "24' Charger 5th Round",
      "24' Charger 6th Round",
      "24' Charger 7th Round",

      "25' Sportstopia 1st Round",
      "25' Chargers 3rd Round",
      "25' Thrashers 3rd Round",
      "25' Charger 4th Round",
      "25' Charger 5th Round",
      "25' Charger 6th Round",
      "25' Charger 7th Round",

      "26' Charger 1st Round",
      "26' Charger 2nd Round",
      "26' Charger 3rd Round",
      "26' Charger 4th Round",
      "26' Charger 5th Round",
      "26' Charger 6th Round",
      "26' Charger 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6da', // Stormbreakers
    draft: [
      "24' Stormbreakers 1st Round",
      "24' Stormbreakers 2nd Round",
      "24' Stormbreakers 3rd Round",
      "24' Stormbreakers 4th Round",
      "24' Stormbreakers 5th Round",
      "24' Stormbreakers 6th Round",
      "24' Stormbreakers 7th Round",

      "25' Stormbreakers 1st Round",
      "25' Stormbreakers 2nd Round",
      "25' Stormbreakers 3rd Round",
      "25' Stormbreakers 4th Round",
      "25' Stormbreakers 5th Round",
      "25' Stormbreakers 6th Round",
      "25' Stormbreakers 7th Round",

      "26' Stormbreakers 1st Round",
      "26' Stormbreakers 2nd Round",
      "26' Stormbreakers 3rd Round",
      "26' Stormbreakers 4th Round",
      "26' Stormbreakers 5th Round",
      "26' Stormbreakers 6th Round",
      "26' Stormbreakers 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6e9', // Turf Monsters
    draft: [
      "24' Turf Monsters 1st Round",
      "24' Red Zone 1st Round",
      "24' Turf Monsters 2nd Round",
      "24' Doom 2nd Round",
      "24' Kingsmen 2nd Round",
      "24' Turf Monsters 3rd Round",
      "24' Turf Monsters 4th Round",
      "24' Turf Monsters 5th Round",
      "24' Turf Monsters 6th Round",
      "24' Turf Monsters 7th Round",

      "25' Turf Monsters 1st Round",
      "25' Turf Monsters 2nd Round",
      "25' Turf Monsters 3rd Round",
      "25' Turf Monsters 4th Round",
      "25' Turf Monsters 5th Round",
      "25' Turf Monsters 6th Round",
      "25' Turf Monsters 7th Round",

      "26' Turf Monsters 1st Round",
      "26' Turf Monsters 2nd Round",
      "26' Turf Monsters 3rd Round",
      "26' Turf Monsters 4th Round",
      "26' Turf Monsters 5th Round",
      "26' Turf Monsters 6th Round",
      "26' Turf Monsters 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6e1', // Doom
    draft: [
      "24' Kingsmen 1st Round",
      "24' Outcasts 1st Round",
      "24' SB Hurricanes 1st Round",
      "24' Thrashers 2nd Round",
      "24' Outcasts 2nd Round",
      "24' Warriors 2nd Round",
      "24' Toppem Spoilers 2nd Round",
      "24' Sportstopia 2nd Round",
      "24' Doom 3rd Round",
      "24' Doom 4th Round",
      "24' Doom 5th Round",
      "24' Doom 6th Round",
      "24' Doom 7th Round",

      "25' Doom 1st Round",
      "25' Valkyries 1st Round",
      "25' Doom 2nd Round",
      "25' Doom 3rd Round",
      "25' Doom 4th Round",
      "25' Doom 5th Round",
      "25' Doom 6th Round",
      "25' Doom 7th Round",

      "26' Doom 1st Round",
      "26' Doom 2nd Round",
      "26' Doom 3rd Round",
      "26' Doom 4th Round",
      "26' Doom 5th Round",
      "26' Doom 6th Round",
      "26' Doom 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6de', // Valkyries
    draft: [
      "24' Valkyries 1st Round",
      "24' Valkyries 2nd Round",
      "24' Valkyries 3rd Round",
      "24' Valkyries 4th Round",
      "24' Valkyries 5th Round",
      "24' Valkyries 6th Round",
      "24' Valkyries 7th Round",

      "25' Valkyries 3rd Round",
      "25' Valkyries 4th Round",
      "25' Valkyries 5th Round",
      "25' Valkyries 6th Round",
      "25' Valkyries 7th Round",

      "26' Valkyries 1st Round",
      "26' Valkyries 2nd Round",
      "26' Valkyries 3rd Round",
      "26' Valkyries 4th Round",
      "26' Valkyries 5th Round",
      "26' Valkyries 6th Round",
      "26' Valkyries 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6d7', // FanCentric
    draft: [
      "24' FanCentric 3rd Round",
      "24' FanCentric 4th Round",
      "24' FanCentric 5th Round",
      "24' FanCentric 6th Round",
      "24' FanCentric 7th Round",

      "25' Sportstopia 2nd Round",
      "25' FanCentric 4th Round",
      "25' FanCentric 5th Round",
      "25' FanCentric 6th Round",
      "25' FanCentric 7th Round",

      "26' FanCentric 1st Round",
      "26' FanCentric 2nd Round",
      "26' FanCentric 3rd Round",
      "26' FanCentric 4th Round",
      "26' FanCentric 5th Round",
      "26' FanCentric 6th Round",
      "26' FanCentric 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6db', // Ghostriders
    draft: [
      "24' Ghostriders 3rd Round",
      "24' Ghostriders 4th Round",
      "24' Ghostriders 5th Round",
      "24' Ghostriders 6th Round",
      "24' Ghostriders 7th Round",

      "25' Ghostriders 3rd Round",
      "25' Ghostriders 4th Round",
      "25' Ghostriders 5th Round",
      "25' Ghostriders 6th Round",
      "25' Ghostriders 7th Round",

      "26' Ghostriders 1st Round",
      "26' Ghostriders 2nd Round",
      "26' Ghostriders 3rd Round",
      "26' Ghostriders 4th Round",
      "26' Ghostriders 5th Round",
      "26' Ghostriders 6th Round",
      "26' Ghostriders 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6e4', // Kingsmen
    draft: [
      "24' Kingsmen 3rd Round",
      "24' Kingsmen 4th Round",
      "24' Kingsmen 5th Round",
      "24' Kingsmen 6th Round",
      "24' Kingsmen 7th Round",

      "25' Kingsmen 1st Round",
      "25' Kingsmen 2nd Round",
      "25' Kingsmen 3rd Round",
      "25' Kingsmen 4th Round",
      "25' Kingsmen 5th Round",
      "25' Kingsmen 6th Round",
      "25' Kingsmen 7th Round",

      "26' Kingsmen 1st Round",
      "26' Kingsmen 2nd Round",
      "26' Kingsmen 3rd Round",
      "26' Kingsmen 4th Round",
      "26' Kingsmen 5th Round",
      "26' Kingsmen 6th Round",
      "26' Kingsmen 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6ea', // Beast
    draft: [
      "24' Beast 2nd Round",
      "24' Beast 3rd Round",
      "24' Beast 4th Round",
      "24' Beast 5th Round",
      "24' Beast 6th Round",
      "24' Beast 7th Round",

      "25' Beast 1st Round",
      "25' Beast 2nd Round",
      "25' Beast 3rd Round",
      "25' Beast 4th Round",
      "25' Beast 5th Round",
      "25' Beast 6th Round",
      "25' Beast 7th Round",

      "26' Beast 1st Round",
      "26' Beast 2nd Round",
      "26' Beast 3rd Round",
      "26' Beast 4th Round",
      "26' Beast 5th Round",
      "26' Beast 6th Round",
      "26' Beast 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6df', // Timberwolves
    draft: [
      "24' Gridiron 2nd Round",
      "24' Timberwolves 3rd Round",
      "24' Timberwolves 4th Round",
      "24' Timberwolves 5th Round",
      "24' Timberwolves 6th Round",
      "24' Timberwolves 7th Round",

      "25' Timberwolves 1st Round",
      "25' Toppem Spoilers 1st Round",
      "25' Timberwolves 2nd Round",
      "25' Timberwolves 2nd Round",
      "25' Timberwolves 3rd Round",
      "25' Timberwolves 4th Round",
      "25' Timberwolves 5th Round",
      "25' Timberwolves 6th Round",
      "25' Timberwolves 7th Round",

      "26' Timberwolves 1st Round",
      "26' Timberwolves 2nd Round",
      "26' Timberwolves 3rd Round",
      "26' Timberwolves 4th Round",
      "26' Timberwolves 5th Round",
      "26' Timberwolves 6th Round",
      "26' Timberwolves 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6dd', // Warriors
    draft: [
      "24' Warriors 1st Round",
      "24' Doom 1st Round",
      "24' Legion 2nd Round",
      "24' Warriors 3rd Round",
      "24' Warriors 4th Round",
      "24' Warriors 5th Round",
      "24' Warriors 6th Round",
      "24' Warriors 7th Round",

      "25' Warriors 1st Round",
      "25' Warriors 2nd Round",
      "25' Warriors 3rd Round",
      "25' Warriors 4th Round",
      "25' Warriors 5th Round",
      "25' Warriors 6th Round",
      "25' Warriors 7th Round",

      "26' Warriors 1st Round",
      "26' Warriors 2nd Round",
      "26' Warriors 3rd Round",
      "26' Warriors 4th Round",
      "26' Warriors 5th Round",
      "26' Warriors 6th Round",
      "26' Warriors 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6e3', // Red Zone
    draft: [
      "24' Red Zone 3rd Round",
      "24' Red Zone 4th Round",
      "24' Red Zone 5th Round",
      "24' Red Zone 6th Round",
      "24' Red Zone 7th Round",

      "25' Red Zone 4th Round",
      "25' Red Zone 5th Round",
      "25' Red Zone 6th Round",
      "25' Red Zone 7th Round",

      "26' Red Zone 1st Round",
      "26' Red Zone 2nd Round",
      "26' Red Zone 3rd Round",
      "26' Red Zone 4th Round",
      "26' Red Zone 5th Round",
      "26' Red Zone 6th Round",
      "26' Red Zone 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6e6', // Empire
    draft: [
      "24' Empire 1st Round",
      "24' Empire 2nd Round",
      "24' Empire 3rd Round",
      "24' Empire 4th Round",
      "24' Empire 5th Round",
      "24' Empire 6th Round",
      "24' Empire 7th Round",

      "25' Empire 1st Round",
      "25' Empire 2nd Round",
      "25' Empire 3rd Round",
      "25' Hammerheads 3rd Round",
      "25' Empire 4th Round",
      "25' Empire 5th Round",
      "25' Empire 6th Round",
      "25' Empire 7th Round",

      "26' Empire 1st Round",
      "26' Empire 2nd Round",
      "26' Empire 3rd Round",
      "26' Empire 4th Round",
      "26' Empire 5th Round",
      "26' Empire 6th Round",
      "26' Empire 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6d1', // Blockchain
    draft: [
      "24' Blockchain 1st Round",
      "24' Blockchain 2nd Round",
      "24' Blockchain 3rd Round",
      "24' Blockchain 4th Round",
      "24' Blockchain 5th Round",
      "24' Blockchain 6th Round",
      "24' Blockchain 7th Round",

      "25' Blockchain 1st Round",
      "25' Blockchain 2nd Round",
      "25' Blockchain 3rd Round",
      "25' Blockchain 4th Round",
      "25' Blockchain 5th Round",
      "25' Blockchain 6th Round",
      "25' Blockchain 7th Round",

      "26' Blockchain 1st Round",
      "26' Blockchain 2nd Round",
      "26' Blockchain 3rd Round",
      "26' Blockchain 4th Round",
      "26' Blockchain 5th Round",
      "26' Blockchain 6th Round",
      "26' Blockchain 7th Round",
    ],
  },
  {
    teamId: '64e5ee7d6e36d01a688fc6ed', // Hammerheads
    draft: [
      "24' Rowdys 2024 1st Round",
      "24' Hammerheads 3rd Round",
      "24' Hammerheads 4th Round",
      "24' Hammerheads 5th Round",
      "24' Hammerheads 6th Round",
      "24' Hammerheads 7th Round",

      "25' Hammerheads 1st Round",
      "25' Hammerheads 2nd Round",
      // "25' Hammerheads 1st Round",
      // "25' Hammerheads 2nd Round",
      "25' Hammerheads 4th Round",
      "25' Hammerheads 5th Round",
      "25' Hammerheads 6th Round",
      "25' Hammerheads 7th Round",

      "26' Hammerheads 1st Round",
      "26' Hammerheads 2nd Round",
      "26' Hammerheads 3rd Round",
      "26' Hammerheads 4th Round",
      "26' Hammerheads 5th Round",
      "26' Hammerheads 6th Round",
      "26' Hammerheads 7th Round",
    ],
  },
]
