export const games = [
  {
    key: 'football',
    name: 'A.Football',
    emoji: '🏈',
    accentColor: '#EF4444',
    tagline: 'A.Football Fantasy',
    imagePath: 'football.png',
    disabled: false,
  },
  {
    key: 'hockey',
    name: 'Hockey',
    emoji: '🏒',
    accentColor: '#3B82F6',
    tagline: 'NHL Fantasy',
    imagePath: 'hockey.png',
    disabled: true,
  },
  {
    key: 'baseball',
    name: 'Baseball',
    emoji: '⚾',
    accentColor: '#F59E0B',
    tagline: 'MLB Fantasy',
    imagePath: 'baseball.png',
    disabled: true,
  },
  {
    key: 'basketball',
    name: 'Basketball',
    emoji: '🏀',
    accentColor: '#F97316',
    tagline: 'NBA Fantasy',
    imagePath: 'basketball.png',
    disabled: true,
  },
  {
    key: 'eleven_fc',
    name: 'Soccer',
    emoji: '⚽',
    accentColor: '#D4A843',
    tagline: 'Eleven F.C',
    imagePath: 'eleven-fc.png',
    disabled: false,
  },
]
